# %%
import os
import shutil
from OMPython import ModelicaSystem
from buildingspy.simulate.Simulator import Simulator

def fmu_export( modeling_environment, model_name, model_directory, output_directory, 
                datasheet_directory, datasheets ,additional_parameters):
    pass

class ParameterImport():

    def __init__(self, model_modifier_list = []):
        
        self._parameters = {}
        self.model_modifiers = model_modifier_list
    
    @property
    def parameters(self):
        return self._parameters

    @parameters.setter
    def parameters(self, parameter_dic):
        if type(parameter_dic) is not dict:
            raise TypeError("'parameters' have to be a dictionary")
        self._parameters = parameter_dic
    
    @property
    def model_modifiers(self):
        return self._model_modifiers

    @model_modifiers.setter
    def model_modifiers(self, model_modifier_list):
        if type(model_modifier_list) is not list:
            raise TypeError("'model_modifier_list' has to be a list")
        for modifier in model_modifier_list:
            if "=" not in modifier:
                raise ValueError("The model modifiers need to be in the following format:e.g. 'redeclare package Medium = Modelica.Media.Water.ConstantPropertyLiquidWater'")
        self._model_modifiers = model_modifier_list    
    
    def read_datasheet(self, datasheet_directory, datasheet_dict): #TODO what if datasheets all in different dir

        import json

        for component, sheet_name in datasheet_dict.items():
            with open(os.path.join(datasheet_directory, sheet_name + '.json')) as file:
                datasheet = json.load(file)
                try:
                    parameters = datasheet['Parameters']
                except KeyError:
                    print(f"The {datasheet} in missing the key 'Parameters'.")
                for parameter in parameters:
                    symbol = parameter['symbol']
                    value = parameter['value']
                    if value != "":
                        self._parameters[f'{component}.{symbol}'] = value
    

    def read_additional_parameters(self, additional_parameters):

        for component in additional_parameters:
            self._parameters[component] = additional_parameters[component]

    

        
class DymolaFmuExport(Simulator, ParameterImport):
    
    def __init__(self, model_name,model_directory, dymola_path, output_directory, packages = [],  model_modifiers = []):
        Simulator.__init__(self, model_name, 'dymola', outputDirectory = output_directory)
        ParameterImport.__init__(self, model_modifier_list=model_modifiers)
        
        self.packages = packages
        self.model_directory = model_directory
        self.dymola_path = dymola_path

    def make_dymola_available(self):
     
        os.environ["PATH"] += os.pathsep + self.dymola_path

    def add_parameters(self):
        for component_symbol, value in self.parameters.items():
            self.addParameters({component_symbol: value})

    def add_model_modifiers(self):

        for modifier in self.model_modifiers:
            self.addModelModifier(modifier) 

    def _get_dymola_commands(self, working_directory, log_file, model_instance, packages):
        s = """
// File autogenerated by _get_dymola_commands_customized\n"""
        
        # Command to open packages
        if packages:
            for pack in packages:
                s+= """openModel("{0}");\n""".format(pack)

        s += """//cd("{working_directory}");
cd("{model_directory}");
openModel("{model_path}");
OutputCPUtime:=true;
""".format(working_directory=working_directory,
           log_file=log_file, 
           model_directory = self.model_directory,
           model_path = f'{self.model_directory}{self.modelName}.mo')
        



        s += "modelInstance={0};\n".format(model_instance)
  
        s += """
translateModelFMU(modelInstance, false, "", "2", "all", false, 2);
"""

        s += """savelog("{0}");\n""".format(log_file)
        if self._exitSimulator:
            s += "Modelica.Utilities.System.exit();\n"
        return s

    def _declare_parameters(self):
        """ Declare list of parameters

        Arg:
            -
        
        Returns:
            dec (string): The model instance with all parameter values and the package redeclarations.
        """

        def to_modelica(arg):
            """ Convert to Modelica array.
            """
            # Check for strings and booleans
            if isinstance(arg, str):                                        
                return arg                                                  
            elif isinstance(arg, bool):                                     
                if arg is True:
                    return 'true'
                else:
                    return 'false'
            try:
                return '{' + ", ".join(to_modelica(x) for x in arg) + '}'
            except TypeError:
                return repr(arg)
        dec = list()

        for k, v in list(self._parameters_.items()):
            # Dymola requires vectors of parameters to be set in the format
            # p = {1, 2, 3} rather than in the format of python arrays, which
            # is p = [1, 2, 3].
            # Hence, we convert the value of the parameter if required.
            s = to_modelica(v)
            dec.append('{param}={value}'.format(param=k, value=s))

        return dec 


    def fmu_export(self):

        # function modified from buldingspy

        # Get directory name. This ensures for example that if the directory is called xx/Buildings
        # then the simulations will be done in tmp??/Buildings
        worDir = self._create_worDir()
        self._simulateDir_ = worDir
        # Copy directory
        shutil.copytree(os.path.abspath(self._packagePath), worDir,
                        ignore=shutil.ignore_patterns('*.svn', '*.git'))        

        # Construct the model instance with all parameter values
        # and the package redeclarations
        dec = self._declare_parameters()
        dec.extend(self._modelModifiers_)
        self.custom_settings = dec.copy()
        mi = '"{mn}({dec})"'.format(mn=self.modelName, dec=','.join(dec))
        
        # Write the Modelica script
        runScriptName = os.path.join(worDir, "run.mos").replace("\\","/")
        with open(runScriptName, mode="w", encoding="utf-8") as fil:
            fil.write(self._get_dymola_commands(
                working_directory=worDir,
                log_file="simulator.log",
                model_instance=mi,
                packages = self.packages))
        # Run script
        print('Compiling...')
        self._runSimulation(runScriptName, self._simulator_.get('timeout'),
                                                                        worDir)


    


class OpenModelicaFmuExport():
    pass


class DataManagement():
    pass




# %%

